[tool.poetry]
name = "storm"
version = "0.1.0"
description = ""
authors = ["Ajay Ratnam <ajayratnam.satheesh@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
fishhook = "^0.1.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
